import React, { useState } from 'react';
import { Alert, ScrollView, View } from 'react-native';
import { Text, useTheme, Button } from 'react-native-paper';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { useApp } from '../context/AppContext';
import { useData } from '../hooks/useData';
import { monthlyWrapped } from '../services/finance';
import { formatINR } from '../utils/money';
import { SectionCard, Kpi, Row } from '../components/ui';
import { palette } from '../theme';

const MONTH_NAMES = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
];

export default function MonthlyWrappedScreen() {
  const theme = useTheme();
  const { userId } = useApp();
  const now = new Date();
  // Default to previous completed month
  const [selectedYear, setSelectedYear] = useState(now.getMonth() === 0 ? now.getFullYear() - 1 : now.getFullYear());
  const [selectedMonth, setSelectedMonth] = useState(now.getMonth() === 0 ? 12 : now.getMonth());
  const [sharing, setSharing] = useState(false);

  const data = useData(() => {
    if (!userId) return null;
    return monthlyWrapped(userId, selectedYear, selectedMonth);
  }, [userId, selectedYear, selectedMonth]);

  const handleShare = async () => {
    if (!data) return;
    setSharing(true);
    try {
      const nwSign = data.net_worth_delta >= 0 ? '+' : '';
      const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <style>
    body { font-family: -apple-system, sans-serif; background: #460073; color: white; margin: 0; padding: 32px; min-height: 100vh; }
    h1 { font-size: 28px; font-weight: 800; margin: 0 0 4px; }
    .subtitle { font-size: 14px; opacity: 0.7; margin-bottom: 32px; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }
    .card { background: rgba(255,255,255,0.12); border-radius: 12px; padding: 16px; }
    .label { font-size: 11px; opacity: 0.7; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 4px; }
    .value { font-size: 22px; font-weight: 800; }
    .sub { font-size: 12px; opacity: 0.7; margin-top: 2px; }
    .footer { margin-top: 32px; font-size: 11px; opacity: 0.4; text-align: center; }
  </style>
</head>
<body>
  <h1>FinVault Wrapped</h1>
  <div class="subtitle">${MONTH_NAMES[selectedMonth - 1]} ${selectedYear}</div>
  <div class="grid">
    <div class="card">
      <div class="label">Net Worth Change</div>
      <div class="value">${nwSign}${formatINR(data.net_worth_delta)}</div>
      <div class="sub">${nwSign}${data.net_worth_delta_pct}%</div>
    </div>
    <div class="card">
      <div class="label">Savings Rate</div>
      <div class="value">${data.savings_rate}%</div>
      <div class="sub">${formatINR(data.income_total - data.expense_total)} saved</div>
    </div>
    <div class="card">
      <div class="label">Top Spend</div>
      <div class="value">${data.top_spend_category}</div>
      <div class="sub">${formatINR(data.top_spend_amount)}</div>
    </div>
    <div class="card">
      <div class="label">Best Investment</div>
      <div class="value">${data.best_asset_name}</div>
      <div class="sub">+${data.best_asset_return_pct}%</div>
    </div>
    <div class="card">
      <div class="label">SIPs</div>
      <div class="value">${data.sip_paid}/${data.sip_total}</div>
      <div class="sub">paid this month</div>
    </div>
    <div class="card">
      <div class="label">Goals On Track</div>
      <div class="value">${data.goals_on_track}/${data.total_goals}</div>
      <div class="sub">financial goals</div>
    </div>
  </div>
  <div class="footer">Generated by FinVault · ${new Date().toLocaleDateString('en-IN')}</div>
</body>
</html>`;
      const { uri } = await Print.printToFileAsync({ html, base64: false });
      const canShare = await Sharing.isAvailableAsync();
      if (canShare) {
        await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: 'Share Monthly Wrapped' });
      } else {
        Alert.alert('Sharing unavailable', 'Your device does not support sharing files.');
      }
    } catch {
      Alert.alert('Error', 'Could not generate PDF. Please try again.');
    } finally {
      setSharing(false);
    }
  };

  const goToPrev = () => {
    if (selectedMonth === 1) { setSelectedMonth(12); setSelectedYear((y) => y - 1); }
    else setSelectedMonth((m) => m - 1);
  };

  const goToNext = () => {
    const isCurrentMonth = selectedYear === now.getFullYear() && selectedMonth === now.getMonth() + 1;
    if (isCurrentMonth) return;
    if (selectedMonth === 12) { setSelectedMonth(1); setSelectedYear((y) => y + 1); }
    else setSelectedMonth((m) => m + 1);
  };

  return (
    <ScrollView
      style={{ flex: 1, backgroundColor: theme.colors.background }}
      contentContainerStyle={{ padding: 16, gap: 16 }}
    >
      {/* Month selector */}
      <View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 }}>
        <Button onPress={goToPrev} icon="chevron-left" mode="text" compact>Prev</Button>
        <Text variant="titleMedium" style={{ fontWeight: '700', color: theme.colors.onSurface }}>
          {MONTH_NAMES[selectedMonth - 1]} {selectedYear}
        </Text>
        <Button onPress={goToNext} icon="chevron-right" mode="text" compact contentStyle={{ flexDirection: 'row-reverse' }}>
          Next
        </Button>
      </View>

      {!data ? (
        <View style={{ alignItems: 'center', paddingVertical: 48, gap: 12 }}>
          <MaterialCommunityIcons name="chart-timeline-variant" size={48} color={theme.colors.onSurfaceVariant} />
          <Text variant="bodyMedium" style={{ color: theme.colors.onSurfaceVariant, textAlign: 'center' }}>
            No data available for this month.{'\n'}Add expenses, assets, or income to see your Wrapped.
          </Text>
        </View>
      ) : (
        <>
          {/* Hero: Net Worth */}
          <SectionCard style={{ backgroundColor: '#460073' }}>
            <View style={{ alignItems: 'center', gap: 4 }}>
              <Text variant="labelSmall" style={{ color: 'rgba(255,255,255,0.6)', textTransform: 'uppercase', letterSpacing: 1 }}>
                Net Worth Change
              </Text>
              <Text variant="displaySmall" style={{ color: 'white', fontWeight: '900', fontVariant: ['tabular-nums'] }}>
                {data.net_worth_delta >= 0 ? '+' : ''}{formatINR(data.net_worth_delta)}
              </Text>
              <Text variant="bodySmall" style={{ color: data.net_worth_delta >= 0 ? palette.good : palette.danger, fontWeight: '700' }}>
                {data.net_worth_delta >= 0 ? '+' : ''}{data.net_worth_delta_pct}% this month
              </Text>
            </View>
          </SectionCard>

          <Row>
            <Kpi label="Income" value={formatINR(data.income_total)} />
            <Kpi label="Expenses" value={formatINR(data.expense_total)} />
          </Row>
          <Row>
            <Kpi
              label="Savings Rate"
              value={`${data.savings_rate}%`}
              subTone={data.savings_rate >= 20 ? 'good' : data.savings_rate >= 10 ? 'warn' : 'bad'}
            />
            <Kpi
              label="Goals On Track"
              value={`${data.goals_on_track}/${data.total_goals}`}
              subTone={data.goals_on_track >= data.total_goals ? 'good' : 'warn'}
            />
          </Row>

          <SectionCard title="Highlights">
            <View style={{ gap: 12 }}>
              <View style={{ flexDirection: 'row', justifyContent: 'space-between' }}>
                <Text variant="bodySmall" style={{ color: theme.colors.onSurfaceVariant }}>Top spending category</Text>
                <Text variant="bodySmall" style={{ fontWeight: '700', color: theme.colors.onSurface }}>
                  {data.top_spend_category} ({formatINR(data.top_spend_amount)})
                </Text>
              </View>
              <View style={{ flexDirection: 'row', justifyContent: 'space-between' }}>
                <Text variant="bodySmall" style={{ color: theme.colors.onSurfaceVariant }}>Best performing asset</Text>
                <Text variant="bodySmall" style={{ fontWeight: '700', color: palette.good }}>
                  {data.best_asset_name} (+{data.best_asset_return_pct}%)
                </Text>
              </View>
              <View style={{ flexDirection: 'row', justifyContent: 'space-between' }}>
                <Text variant="bodySmall" style={{ color: theme.colors.onSurfaceVariant }}>SIPs paid this month</Text>
                <Text variant="bodySmall" style={{ fontWeight: '700', color: theme.colors.onSurface }}>
                  {data.sip_paid} of {data.sip_total}
                </Text>
              </View>
            </View>
          </SectionCard>

          <Button
            mode="contained"
            onPress={handleShare}
            loading={sharing}
            disabled={sharing}
            icon="share-variant"
            style={{ borderRadius: 12 }}
          >
            Share as PDF
          </Button>
        </>
      )}
    </ScrollView>
  );
}
